In [1]:
import numpy as np

x = np.array([[1,2,2],[4,5,6]])
y = np.array([[7,8],[9,3],[2,1]])

print(x,"\n")
print(y)

[[1 2 2]
 [4 5 6]] 

[[7 8]
 [9 3]
 [2 1]]


In [2]:
p = np.array([[4,7,1],[4,3,2]]) 
print("x =\n", x)
print("\np =\n", p)
print("\nx + p =\n",x + p)

x =
 [[1 2 2]
 [4 5 6]]

p =
 [[4 7 1]
 [4 3 2]]

x + p =
 [[5 9 3]
 [8 8 8]]


In [3]:
print("x =\n", x) 
print("\np =\n", p) 
print("\nx - p =\n",x - p)

x =
 [[1 2 2]
 [4 5 6]]

p =
 [[4 7 1]
 [4 3 2]]

x - p =
 [[-3 -5  1]
 [ 0  2  4]]


In [4]:
print(5 * x)

[[ 5 10 10]
 [20 25 30]]


In [5]:
print("x =\n", x) 
print("\ny =\n", y) 
print("\nmatmul(x,y) =") 
print(np.matmul(x,y))

x =
 [[1 2 2]
 [4 5 6]]

y =
 [[7 8]
 [9 3]
 [2 1]]

matmul(x,y) =
[[29 16]
 [85 53]]


In [6]:
print(x @ y)

[[29 16]
 [85 53]]


In [7]:
v1 = np.array([1,2,3]) 
v2 = np.array([4,5,6]) 
print (np.dot(v1,v2))

32


In [9]:
print(np.inner(v1,v2))

32


In [10]:
print(np.divide(x,2))

[[0.5 1.  1. ]
 [2.  2.5 3. ]]


In [11]:
print(x/2)

[[0.5 1.  1. ]
 [2.  2.5 3. ]]


In [12]:
print(np.divide(x,p))

[[0.25       0.28571429 2.        ]
 [1.         1.66666667 3.        ]]


In [13]:
print(x/p)

[[0.25       0.28571429 2.        ]
 [1.         1.66666667 3.        ]]


In [14]:
s = np.array([[1,2,3], [14,25,36],[74,38,29]]) 
print(np.linalg.det(s))

-81.00000000000038


In [15]:
s_inv = np.linalg.inv(s) 
print(s_inv)

[[  7.9382716   -0.69135802   0.03703704]
 [-27.87654321   2.38271605  -0.07407407]
 [ 16.27160494  -1.35802469   0.03703704]]


In [16]:
print( np.matmul(s,s_inv))

[[ 1.00000000e+00  0.00000000e+00 -1.38777878e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 5.68434189e-14 -7.10542736e-15  1.00000000e+00]]


In [17]:
M1 = np.array([[1, 2], [3, 5]]) 
M2 = np.array([1, 2])
A = np.linalg.solve(M1, M2) 
print(A)

[-1.  1.]


In [18]:
print(1 * -1 + 2 * 1)

1


In [21]:
print(3 * -1 + 5 * 1)

2


In [22]:
M1 = np.array([[1, 2], [2, 4]]) 
M2 = np.array([1, 3])
A = np.linalg.solve(M1, M2) 
print(A)

LinAlgError: Singular matrix